# Generated by Django 3.2.13 on 2023-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
