export const CREATE_WISHLIST_SUCCESS = 'CREATE_WISHLIST_SUCCESS';
export const CREATE_WISHLIST_FAILURE = 'CREATE_WISHLIST_FAILURE';
export const FETCH_WISHLISTS_SUCCESS = 'FETCH_WISHLISTS_SUCCESS';
export const FETCH_WISHLISTS_FAILURE = 'FETCH_WISHLISTS_FAILURE';
export const FETCH_WISHLIST_DETAIL_SUCCESS = 'FETCH_WISHLIST_DETAIL_SUCCESS';
export const FETCH_WISHLIST_DETAIL_FAILURE = 'FETCH_WISHLIST_DETAIL_FAILURE';

export const CREATE_WISHLIST_REQUEST = 'CREATE_WISHLIST_REQUEST';
export const FETCH_WISHLIST_DETAIL_REQUEST = 'FETCH_WISHLIST_DETAIL_REQUEST';
export const FETCH_WISHLISTS_REQUEST = 'FETCH_WISHLISTS_REQUEST';
